book_rental_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from books import views

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('books/', include('books.urls', namespace='books')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('list/', views.BooksList.as_view(), name='books_list'),
    path('list/<category_id>/', views.CategoryBooksList, name='category_books_list'),
    path('my_rentals/', views.RentalBooksList.as_view(), name='my_rentals'),
    path('<int:book_id>/detail/', views.BookDetail.as_view(), name='book_detail'),
    path('<int:book_id>/rent/', views.BookRent, name='book_rent'),
    path('<int:book_id>/return/', views.BookReturn, name='book_return'),
    path('return_books/', views.BookReturnList, name='return_books'),
    path('create/', views.BookCreate.as_view(), name='book_create'),
    path('search/', views.BookSearch, name='book_search'),
]

books/models.py
from django.db import models

from accounts.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        ordering = ['name']  
    
    def __str__(self):
        return self.name

class Book(models.Model):
    category = models.ForeignKey(Category, related_name='books',on_delete=models.CASCADE)
    title = models.CharField(max_length=200,unique=True)
    author = models.CharField(max_length=200)
    publisher = models.CharField(max_length=200)
    stock = models.IntegerField(default=0)
    summary = models.TextField()
    like = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class Books_rental(models.Model):
    rental_date = models.DateField()
    return_date = models.DateField(null=True, blank=True)
    book = models.ForeignKey(Book, related_name='rentals', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='rental_books', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} rental "{self.book}"'

books/views.py
from django.utils import timezone
from django.db.models import Q
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404, redirect, render ,get_list_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator

from .models import Book, Books_rental, Category

# Create your views here.

def HomePage(request):
    latest_books = Book.objects.all().order_by('-created')[:5]
    like_books = Book.objects.all().order_by('-like')[:10]
    return render(request, 'home.html',{'latest_books':latest_books,'like_books':like_books})

class BooksList(generic.ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'books/books_list.html'
    
    paginate_by = 5
    
def CategoryBooksList(request, category_id):
    books = Book.objects.filter(category=category_id)
    category = get_object_or_404(Category, id=category_id)
    return render(request, 'books/books_list.html', {'books':books, 'category':category})
    
class BookDetail(generic.DetailView):
    model = Book
    pk_url_kwarg = 'book_id'
    context_object_name = 'book'
    template_name = 'books/book_detail.html'

class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Book
    fields = ['category','title','author','publisher','stock','summary']
    context_object_name = 'form'
    redirect_field_name = 'accounts:login'
    template_name = 'books/book_create.html'
    permission_required = 'books.add_book'
    success_url = reverse_lazy('books:books_list')
    
class RentalBooksList(LoginRequiredMixin, generic.ListView):
    model = Books_rental
    context_object_name = 'rental_books'
    template_name = 'books/rental_list.html'
    redirect_field_name = 'accounts/login'
    
    def get_queryset(self):
        return Books_rental.objects.filter(user=self.request.user)

@login_required
def BookRent(request, book_id):
    if request.user.is_anonymous :
        return redirect('accounts:login')
    else:
        book = get_object_or_404(Book, id=book_id)
        if book.stock > 0 :
            Books_rental.objects.create(user=request.user,book=book,rental_date=timezone.localdate())
            book.stock -= 1
            book.like += 1
            book.save()
            return redirect('books:my_rentals')
        else:
            return redirect('books:books_list')

@login_required
def BookReturn(request, book_id):
    if request.method == 'POST':
        book = get_object_or_404(Book, id=book_id)
        rental_book = Books_rental.objects.filter(book=book, user=request.user, book_return=False)[0]
        book.stock += 1
        rental_book.return_date = timezone.localdate()
        book.save()
        rental_book.save()
    return redirect('books:my_rentals')

@login_required
def BookReturnList(request):
    if request.user.is_superuser:
        not_rental_books = Books_rental.objects.filter(return_date=None, rental_date__lt=timezone.localdate()+timezone.timedelta(weeks=1))
        return render(request, 'books/not_return_list.html', {'not_rental_books':not_rental_books})
    else:
        return redirect('books:books_list')
    

def BookSearch(request):
    word = request.GET.get('word')
    print(word)
    books = Book.objects.filter(Q(title__icontains=word)|Q(author__icontains=word))
    
    paginator = Paginator(books, 5)
    
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    return render(request, 'books/books_list.html', {
        'word': word,
        'books': page.object_list,
        'page_obj': page,
        'paginator': paginator,
    })

    

templates/books/book_create.html
{% extends 'base.html' %}

{% block contents %}
    <h5>Add Book</h5>
    <hr>
    <form action="{% url 'books:book_create' %}" method="post">
        {% for field, errors in form.errors.items %}
            <ul class="errorlist">
            {% for error in errors %}
                <li class='alert alert-danger'>{{ error }}</li>
            {% endfor %}
            </ul>
        {% endfor %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Ctegory</label>
            <br>
            {{ form.category }}
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Title</label>
            <br>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Author</label>
            <br>
            {{ form.author }}
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Publisher</label>
            <br>
            {{ form.publisher }}
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Stock</label>
            <br>
            {{ form.stock }}
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Summary</label>
            <br>
            {{ form.summary }}
        </div>
        {% csrf_token %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <p><input class='btn btn-outline-dark' type="submit" value="Add"></p>
        </div>
    </form>
{% endblock contents %}

templates/books/book_detail.html
{% extends 'base.html' %}

{% load static %}

{% block contents %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{% static 'img/default.jpg' %}" alt="..." /></div>
                <div class="col-md-6">
                    <h1 class="display-5 fw-bolder">{{ book.title }}</h1>
                    <div class="fs-5 mb-5">
                        <span class="fst-italic fw-light">{{ book.author }}</span>
                    </div>
                    <p class="lead">{{ book.summary }}</p>
                    <a class='btn btn-outline-dark' href="{% url "books:book_rent" book.id %}">Rental</a>
                </div>
            </div>
        </div>
    </section>
{% endblock contents %}

templates/books/books_list.html
{% extends 'base.html' %}

{% block contents %}
    {% if category %}
        <h5> {{ category.name }} Books List</h5>
    {% elif word %}
        <h5> {{ word }} Books List</h5>
    {% else %}
        <h5>All Books List</h5>
    {% endif %}
    <hr>
    {% for book in books %}
        <div class="card mt-2">
            <div class="card-header">
                <a class="text-decoration-none text-secondary-emphasis " href="{% url 'books:category_books_list' book.category.id %}">{{ book.category }}</a>
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                <p><a class='text-decoration-none fs-4 text-secondary-emphasis' href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a><br></p>
                <footer class="blockquote-footer fs-6 fst-italic">{{ book.author }}</footer>
                </blockquote>
            </div>
        </div>
    {% endfor %}
    {% include 'pagination.html' %}
{% endblock contents %}

templates/books/not_return_list.html
{% extends 'base.html' %}

{% block contents %}
    <h5>Not Return List</h5>
    <hr>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Book</th>
            <th scope="col">User</th>
            <th scope="col">Rental</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for not_rental_book in not_rental_books %}
            <th scope="row">{{ not_rental_book.book }}</th>
            <td>{{ not_rental_book.user }} ( {{ not_rental_book.user.phone}} )</td>
            <td>{{ not_rental_book.rental_date|date:"Y-m-d" }}</td>
            {% endfor %}
        </tr>
    </tbody>
    </table>
{% endblock contents %}

templates/books/rental_list.html
{% extends 'base.html' %}

{% block contents %}
    <h5>My Rental List</h5>
    <hr>
    {% for rental in rental_books %}
        {% if not rental.book_return %}
            <form class="alert alert-dark" action="{% url 'books:book_return' rental.book.id %}" method="post">
                <a class='text-decoration-none text-secondary-emphasis fs-5' href="{% url 'books:book_detail' rental.book.id %}">{{ rental.book.title }}</a>
                <span class="m-5">{{ rental.rental_date|date:"Y-m-d" }}</span>
                {% csrf_token %}
                <span class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <input class="btn btn-outline-dark" type="submit" value="Return">
                </span>
            </form>
        {% endif %}
    {% endfor %}
{% endblock contents %}