accounts/urls.py
from django.urls import path

from . import views

app_name='accounts'
urlpatterns = [
    path('register/',views.RegisterUser, name='register'),
    path('login/',views.LoginUser, name='login'),
    path('logout/',views.LogoutUser, name='logout'),
    path('update/',views.UpdateUser, name='update'),
    path('changePW/',views.ChangePWUser, name='changePW'),
]

book_rental_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from books import views

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('books/', include('books.urls', namespace='books')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path

from . import views

app_name = 'books'
urlpatterns = [
    path('list/', views.BooksList.as_view(), name='books_list'),
    path('list/<category_id>/', views.CategoryBooksList, name='category_books_list'),
    path('my_rentals/', views.RentalBooksList.as_view(), name='my_rentals'),
    path('<int:book_id>/detail/', views.BookDetail.as_view(), name='book_detail'),
    path('<int:book_id>/rent/', views.BookRent, name='book_rent'),
    path('<int:book_id>/return/', views.BookReturn, name='book_return'),
    path('return_books/', views.BookReturnList, name='return_books'),
    path('create/', views.BookCreate.as_view(), name='book_create'),
    path('search/', views.BookSearch, name='book_search'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/home.css' %}" rel="stylesheet" />
    {% block css %}{% endblock css %}
    <title>Book Rental</title>
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light">
                <a class='fw-bold text-decoration-none text-black' href="{% url 'home' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
                    <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                    </svg>
                    Library
                </a>
            </div>
            <div class="list-group list-group-flush">
                <div class="btn-group dropend">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 " href="{% url 'books:books_list' %}">Books List</a>
                    {% block category %}
                    <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></button>
                    <ul class="dropdown-menu">
                        <!-- Dropdown menu links -->
                        {% for category in categories %}
                            <li><a class="dropdown-item" href="{% url 'books:category_books_list' category.id %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% endblock category %}
                </div>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Menu1</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Menu2</a>
                {% if request.user.is_superuser %}
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'books:book_create' %}">Books Add</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'books:return_books' %}">Not Return List</a>
                {% endif %}
                <form class='d-flex flex-row m-2' method="GET" action="{% url 'books:book_search' %}">    
                    <input class="form-control me-2" type="text" placeholder="Search" name="word" value='{{ word }}'>
                    <button class="btn btn-outline-success" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                        </svg>
                    </button>
                </form>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-outline-dark" id="sidebarToggle">Menu</button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            {% if request.user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'books:my_rentals' %}">My Rental</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.username }}</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'accounts:update' %}">Update</a>
                                        <a class="dropdown-item" href="{% url 'accounts:changePW' %}">ChangePW</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                                    </div>
                                </li>
                            {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" >Login</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class='p-3'>
                {% block contents %}
    
                {% endblock contents %}
            </div>
        </div>
    </div>

    {% block script %}
    
    {% endblock script %}
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/home.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block contents %}
    <div class="d-flex flex-column mb-3">
        <div class="p-2">
            <h5>Recent Book</h5>
            <hr>
            <ol class="list-group">
                {% for book in latest_books %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <span class="badge bg-secondary">
                        New
                    </span>
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{ book.title }}</div>
                    </div>
                    <span class="badge bg-transparent text-body">Add : {{ book.created|date:"Y-m-d" }}</span>
                </li>
                {% endfor %}
            </ol>
        </div>
        <div class="p-2">
            <h5>Best Rent Top 10</h5>
            <hr>
            <ol class="list-group list-group-numbered">
                {% for book in like_books %}
                    {% if book.like > 0 %}
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                            <div class="fw-bold">{{ book.title }}</div>
                            </div>
                            <span class="badge bg-transparent text-body">Rent : {{ book.like }}</span>
                        </li>
                    {% endif %}
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock contents %}

templates/pagination.html
<nav aria-label="Page navigation example" class='fixed-bottom'>
    <ul class="pagination justify-content-center mt-3">
        <li class="page-item">
            {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{page_obj.previous_page_number}}{% if word %}&word={{word}}{% endif %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
            {% else %}
            <a class="page-link disabled" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            {% endif %}
        </li>
        {% for page in paginator.page_range %}
                <li class="page-item {% if page == page_obj.number %}active{% endif %}"><a class="page-link" href="?page={{page}}{% if word %}&word={{word}}{% endif %}">{{page}}</a></li>
        {% endfor %}
        <li class="page-item">
            {% if page_obj.has_next %}
            <a class="page-link" href="?page={{page_obj.next_page_number}}{% if word %}&word={{word}}{% endif %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            </a>
            {% else %}
            <a class="page-link disabled" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
        </li>
    </ul>
</nav>